# Generated by Django 5.0.4 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
