# Generated by Django 5.0.4 on 2024-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_patient_user_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, default='/team-3.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='proof',
            field=models.FileField(upload_to='proofs/'),
        ),
    ]
