# Generated by Django 5.0.4 on 2024-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, default='/L-NU_LOGO.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=13),
        ),
    ]
