# Generated by Django 5.0.4 on 2024-08-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_medicalcertificate_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalcase',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BPMonitoring',
        ),
        migrations.DeleteModel(
            name='DentalCase',
        ),
        migrations.DeleteModel(
            name='MedicalCase',
        ),
        migrations.DeleteModel(
            name='MedicalCertificate',
        ),
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
