# Generated by Django 5.0.4 on 2024-09-05 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_patient_birthdate_patient_age_and_more'),
        ('base', '0005_dentalcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('In Queue', 'In Queue')], default='Pending', max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient')),
            ],
        ),
    ]
