# Generated by Django 5.0.4 on 2024-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_vaccination_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='next_dose_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
