# Generated by Django 5.0.4 on 2024-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_vaccination_next_dose_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcertificaterequest',
            name='patient_record',
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=12),
        ),
    ]
