# Generated by Django 5.0.4 on 2024-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_medicalcertificaterequest_patient_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Received', 'Received')], default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Issued', 'Issued'), ('Denied', 'Denied')], default='Pending', max_length=12),
        ),
    ]
