# Generated by Django 5.0.4 on 2024-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_medicalcertificate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
