# Generated by Django 5.1.1 on 2024-09-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_medicalcertificate_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcertificaterequest',
            name='patient',
        ),
        migrations.DeleteModel(
            name='MedicalCertificate',
        ),
        migrations.DeleteModel(
            name='MedicalCertificateRequest',
        ),
    ]
