# Generated by Django 5.0.4 on 2024-10-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_medicine_critical_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.medicalcertificaterequest'),
        ),
    ]
