# Generated by Django 5.0.4 on 2024-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_medicalcertificate_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
