# Generated by Django 5.0.4 on 2024-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_medicalcertificate_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Notified', 'Notified'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('In Queue', 'In Queue')], default='Pending', max_length=12),
        ),
    ]
