# Generated by Django 5.0.4 on 2024-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_appointmentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='or_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
